[package]
name = "esp32c3-display-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "1.0.0-rc.0", features = ["esp32c3", "unstable"] }
esp-backtrace = { version = "0.15.0", features = ["esp32c3", "panic-handler", "println"] }
esp-println = { version = "0.13.0", features = ["esp32c3", "log"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c3"] }
esp-wifi = { version = "0.15.1", features = ["esp32c3", "ble", "builtin-scheduler", "esp-alloc", "log-04"] }
esp-alloc = "0.8.0"
smoltcp = { version = "0.12.0", default-features = false, features = ["medium-ethernet", "proto-ipv4", "proto-dhcpv4", "socket-tcp", "socket-dhcpv4", "socket-udp", "async"] }
heapless = "0.8"
log = "0.4"
embedded-graphics = "0.8"
embedded-hal-bus = "0.3"
mipidsi = "0.9"
embedded-io = "0.6"
trouble-host = { version = "0.8.0", default-features = false, features = ["peripheral", "gatt"] }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = false
opt-level = 's'
overflow-checks = false
